/**
 * Preview deploy management.
 * Creates ephemeral deployments for testing branches/commits.
 */

import { $ } from "bun";
import { readFile, writeFile, readdir, unlink } from "fs/promises";
import { join, basename } from "path";
import { getDeploymentByPath } from "./storage.js";

export interface Preview {
  hash: string;
  gitRef: string;
  url: string;
  createdAt: string;
}

/**
 * Generate a short hash from a git ref.
 */
async function getGitCommitHash(projectPath: string, ref: string): Promise<string> {
  const result = await $`git rev-parse --short=7 ${ref}`.cwd(projectPath).quiet();
  if (result.exitCode !== 0) {
    throw new Error(`Invalid git ref: ${ref}`);
  }
  return result.stdout.toString().trim();
}

/**
 * Get the server IP from the base deploy.yml.
 */
async function getServerIp(projectPath: string): Promise<string> {
  const deployPath = join(projectPath, "config", "deploy.yml");
  const content = await readFile(deployPath, "utf-8");

  // Parse servers from YAML (simple regex since it's our generated format)
  const match = content.match(/servers:\n\s+-\s+(\d+\.\d+\.\d+\.\d+)/);
  if (!match) {
    throw new Error("Could not find server IP in deploy.yml");
  }
  return match[1];
}

/**
 * Ensure secrets-common exists for destination deploys.
 * Kamal looks for .kamal/secrets-common for destinations.
 */
async function ensureSecretsCommon(projectPath: string): Promise<void> {
  const secretsPath = join(projectPath, ".kamal", "secrets");
  const secretsCommonPath = join(projectPath, ".kamal", "secrets-common");

  try {
    // Check if secrets-common already exists
    await readFile(secretsCommonPath);
  } catch {
    // Copy secrets to secrets-common
    try {
      const secrets = await readFile(secretsPath, "utf-8");
      await writeFile(secretsCommonPath, secrets);
    } catch {
      // No secrets file exists
    }
  }
}

/**
 * Create a Kamal destination config for a preview.
 */
async function createDestinationConfig(
  projectPath: string,
  hash: string,
  serverIp: string
): Promise<string> {
  const destPath = join(projectPath, "config", `deploy.preview-${hash}.yml`);
  const previewHost = `preview-${hash}.${serverIp}.nip.io`;

  const content = `# Preview deployment - generated by ship-it
# Hash: ${hash}
# Created: ${new Date().toISOString()}

proxy:
  host: ${previewHost}
  ssl: true
`;

  await writeFile(destPath, content);
  return destPath;
}

/**
 * Create a preview deployment.
 */
export async function createPreview(
  projectPath: string,
  gitRef: string = "HEAD"
): Promise<Preview> {
  // Verify this is a ship-it managed project
  const deployment = await getDeploymentByPath(projectPath);
  if (!deployment) {
    throw new Error("Not a ship-it managed project. Run 'ship-it' first to set up deployment.");
  }

  // Get commit hash for the ref
  const hash = await getGitCommitHash(projectPath, gitRef);
  const serverIp = await getServerIp(projectPath);

  console.log(`Creating preview for ${gitRef} (${hash})...`);

  // Create destination config
  const destPath = await createDestinationConfig(projectPath, hash, serverIp);
  console.log(`Created destination config: ${basename(destPath)}`);

  // Ensure secrets-common exists for destination deploys
  await ensureSecretsCommon(projectPath);

  // Checkout the ref (stash current changes if needed)
  const stashResult = await $`git stash`.cwd(projectPath).quiet();
  const hadChanges = !stashResult.stdout.toString().includes("No local changes");

  try {
    // Deploy to the preview destination
    console.log(`Deploying to preview-${hash}...`);
    const proc = Bun.spawn(["kamal", "deploy", "-d", `preview-${hash}`], {
      cwd: projectPath,
      stdout: "inherit",
      stderr: "inherit",
    });

    const exitCode = await proc.exited;
    if (exitCode !== 0) {
      throw new Error(`kamal deploy failed with exit code ${exitCode}`);
    }
  } finally {
    // Restore stashed changes
    if (hadChanges) {
      await $`git stash pop`.cwd(projectPath).quiet();
    }
  }

  const preview: Preview = {
    hash,
    gitRef,
    url: `https://preview-${hash}.${serverIp}.nip.io`,
    createdAt: new Date().toISOString(),
  };

  console.log(`\nPreview deployed: ${preview.url}`);
  return preview;
}

/**
 * List active previews for a project.
 */
export async function listPreviews(projectPath: string): Promise<Preview[]> {
  const configDir = join(projectPath, "config");
  const previews: Preview[] = [];

  try {
    const files = await readdir(configDir);
    const serverIp = await getServerIp(projectPath);

    for (const file of files) {
      const match = file.match(/^deploy\.preview-([a-f0-9]+)\.yml$/);
      if (match) {
        const hash = match[1];
        const content = await readFile(join(configDir, file), "utf-8");

        // Extract created date from comment
        const dateMatch = content.match(/# Created: (.+)/);
        const createdAt = dateMatch ? dateMatch[1] : "unknown";

        previews.push({
          hash,
          gitRef: hash, // We don't store the original ref, just the hash
          url: `https://preview-${hash}.${serverIp}.nip.io`,
          createdAt,
        });
      }
    }
  } catch {
    // No config dir or can't read
  }

  return previews;
}

/**
 * Delete a preview deployment.
 */
export async function deletePreview(projectPath: string, hash: string): Promise<void> {
  // Verify this is a ship-it managed project
  const deployment = await getDeploymentByPath(projectPath);
  if (!deployment) {
    throw new Error("Not a ship-it managed project.");
  }

  const destPath = join(projectPath, "config", `deploy.preview-${hash}.yml`);

  // Remove the container using kamal
  console.log(`Removing preview-${hash} container...`);
  try {
    const proc = Bun.spawn(["kamal", "app", "remove", "-d", `preview-${hash}`], {
      cwd: projectPath,
      stdout: "inherit",
      stderr: "inherit",
    });
    await proc.exited;
  } catch {
    // Container might not exist, continue anyway
  }

  // Delete the destination config
  try {
    await unlink(destPath);
    console.log(`Deleted destination config: deploy.preview-${hash}.yml`);
  } catch {
    console.log(`Config file not found: deploy.preview-${hash}.yml`);
  }

  console.log(`Preview ${hash} deleted.`);
}
